language: python
python:
 - 3.6
cache: pip
# command to install dependencies
install:
  - pip install -r app/requirements.txt
# command to run tests
script:
#  - python -m unittest
  - python simple_script.py