language: python
python:
 - 3.6
cache: pip
# command to install dependencies
install:
  - pip install -r app/requirements.txt
  - pip install -r build_requirements.txt
# command to run tests
script:
#  - python -m unittest
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bash ./travis/run_on_non_pull_requests; fi'
  - python changelog_test.py $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_BRANCH
